### ISSUE TITLE
Error while using pop3fetcher plugin with roundcube 1.3

### ISSUE THREAD

**Issue by GeorgesHarrison** [morepaolo/roundcube-pop3fetcher#24]
Hi,

I know the pop3fetcher plugin has not been tested with the 1.3 version of roundcube but i tried to use it and I get the following error when trying to go in the parameters :

PHP Fatal error:  Uncaught Error: Call to undefined function get_input_value() in /mail/plugins/pop3fetcher/pop3fetcher.php:211
Stack trace:
#0 /mail/program/lib/Roundcube/rcube_plugin_api.php(439): pop3fetcher->settings(Array)
#1 /mail/program/steps/settings/func.inc(1247): rcube_plugin_api->exec_hook('preferences_lis...', Array)
#2 /mail/program/steps/settings/func.inc(74): rcmail_user_prefs()
#3 /mail/program/include/rcmail_output_html.php(1148): rcmail_sections_list(Array)
#4 [internal function]: rcmail_output_html->xml_command(Array)
#5 /mail/program/include/rcmail_output_html.php(1014): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#6 /mail/program/include/rcmail_output_html.php(635): rcmail_output_html->parse_xml('<roundcube:obje...')
#7 /mail/program/include/rcmail_output_html.php(489): rcmail_output_html->parse('settings', false)
#8 /mail/index.php(316): rcmail_output_html->send('setti in /mail/plugins/pop3fetcher/pop3fetcher.php on line 211

I guess the current pop3fetcher plugin needs a fix to make it work with the current stable version of roundcube.

Thx for your work !

GH

**Comment by nurbles** [comment]
I'm also having problems with pop3fetcher 1.9.1 and roundcube 1.3.0.  With pop3fetcher enabled, I can no longer load the roundcube settings page.  Apache writes this to the error log (one change: I replaced our web address with mysite.example.com):

[Wed Jul 19 14:00:13.319561 2017] [:error] [pid 30787] [client 97.68.84.154:61497] PHP Fatal error:  Uncaught Error: Call to undefined function rep_specialchars_output() in /usr/share/roundcube/plugins/pop3fetcher/pop3fetcher.php:236\nStack trace:\n#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): pop3fetcher->settings(Array)\n#1 /usr/share/roundcube/program/steps/settings/func.inc(1247): rcube_plugin_api->exec_hook('preferences_lis...', Array)\n#2 /usr/share/roundcube/program/steps/settings/func.inc(74): rcmail_user_prefs()\n#3 /usr/share/roundcube/program/include/rcmail_output_html.php(1148): rcmail_sections_list(Array)\n#4 [internal function]: rcmail_output_html->xml_command(Array)\n#5 /usr/share/roundcube/program/include/rcmail_output_html.php(1014): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')\n#6 /usr/share/roundcube/program/include/rcmail_output_html.php(635): rcmail_output_html->parse_xml('<roundcube:obje...')\n#7 /usr/share/roundcube/program/include/rcmail_output_html.php(489): rcmail_output_html->parse('settings', false)\n#8 /usr/share/roundcube/index.php(31 in /usr/share/roundcube/plugins/pop3fetcher/pop3fetcher.php on line 236, referer: https://mysite.example.com/cube/?_task=mail&_mbox=INBOX

**Comment by Zilwil** [comment]
I went through the same problem during a stormlike update of my debian. This is the patch (if someone has the time to commit that to github) :
1. download and install the master version of pop3fetcher (not the 1.9.1 version)
2. edit pop3fetcher.php:
- line 372: replace create_attrib_string by html::attrib_string
- replace all occurrences of rep_specialchars_output with html::quote by hand or with sed : 
`sed -i -- 's/rep_specialchars_output/html::quote/g' path/to/pop3fetcher.php`
- line 459: replace rcmail_build_folder_tree by $this->rcmail->build_folder_tree
- line 462: replace rcmail_render_folder_tree_select by $this->rcmail->render_folder_tree_select
I didn't test the add function because I already have a working config.
Hope it will help others, cheers.a

**Comment by gloony** [comment]
Miss something for saving and editing account.

Replace the value RCUBE_INPUT_POST by INPUT_POST
And for editing, you must replace RCUBE_INPUT_GET by INPUT_GET

Something doesn't work when save of add, but I don't find what already. By the way, if you enter the parameters in DB directly it work.
I will probably make a update when I find what is broken.

**Comment by gloony** [comment]
I got it, I make a Pull Request for the update
Commit: #26
